version: "3.3"

volumes:
  grafana-data:
  loki-data:

services:
  loki:
    image: grafana/loki:2.9.0
    container_name: master_loki
    restart: unless-stopped
    volumes:
    - ./loki-config.yml:/mnt/config/loki-config.yml
    - loki-data:/loki
    ports:
    - 3100:3100
    command: 
    - '-config.file=/mnt/config/loki-config.yml'

  grafana:
    image: grafana/grafana:latest
    container_name: master_grafana
    restart: unless-stopped
    volumes:
    - grafana-data:/var/lib/grafana
    ports:
    - 3000:3000