version: "3.3"

volumes:
  grafana-data:
  loki-data:

services:
  loki:
    image: grafana/loki:2.4.1
    container_name: master_loki
    restart: unless-stopped
    volumes:
    - ./loki-config.yml:/mnt/config/loki-config.yml
    - loki-data:/loki
    command: 
    - '-config.file=/mnt/config/loki-config.yml'

  nginx:
    image: nginx:latest
    volumes:
      - nginx.conf:/etc/nginx/nginx.conf
      - .htpasswd:/etc/nginx/.htpasswd
    ports:
      - "3100:80"
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:latest
    container_name: master_grafana
    restart: unless-stopped
    volumes:
    - grafana-data:/var/lib/grafana
    ports:
    - 3000:3000